//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailCheck.Dmarc.Evaluator.Explainers {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DmarcExplainerResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DmarcExplainerResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MailCheck.Dmarc.Evaluator.Explainers.DmarcExplainerResource", typeof(DmarcExplainerResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AdkimRelaxedExplanation {
            get {
                return ResourceManager.GetString("AdkimRelaxedExplanation", resourceCulture);
            }
        }
        
        internal static string AdkimStrictExplanation {
            get {
                return ResourceManager.GetString("AdkimStrictExplanation", resourceCulture);
            }
        }
        
        internal static string AspfRelaxedExplanation {
            get {
                return ResourceManager.GetString("AspfRelaxedExplanation", resourceCulture);
            }
        }
        
        internal static string AspfStrictExplanation {
            get {
                return ResourceManager.GetString("AspfStrictExplanation", resourceCulture);
            }
        }
        
        internal static string FailureOptionsDExplanation {
            get {
                return ResourceManager.GetString("FailureOptionsDExplanation", resourceCulture);
            }
        }
        
        internal static string FailureOptionsOneExplanation {
            get {
                return ResourceManager.GetString("FailureOptionsOneExplanation", resourceCulture);
            }
        }
        
        internal static string FailureOptionsSExplanation {
            get {
                return ResourceManager.GetString("FailureOptionsSExplanation", resourceCulture);
            }
        }
        
        internal static string FailureOptionsZeroExplanation {
            get {
                return ResourceManager.GetString("FailureOptionsZeroExplanation", resourceCulture);
            }
        }
        
        internal static string PercentExplanation {
            get {
                return ResourceManager.GetString("PercentExplanation", resourceCulture);
            }
        }
        
        internal static string PolicyNoneExplanation {
            get {
                return ResourceManager.GetString("PolicyNoneExplanation", resourceCulture);
            }
        }
        
        internal static string PolicyQuarantineExplanation {
            get {
                return ResourceManager.GetString("PolicyQuarantineExplanation", resourceCulture);
            }
        }
        
        internal static string PolicyRejectExplanation {
            get {
                return ResourceManager.GetString("PolicyRejectExplanation", resourceCulture);
            }
        }
        
        internal static string PolicyUnknownExplanation {
            get {
                return ResourceManager.GetString("PolicyUnknownExplanation", resourceCulture);
            }
        }
        
        internal static string ReportFormatAFRFExplanation {
            get {
                return ResourceManager.GetString("ReportFormatAFRFExplanation", resourceCulture);
            }
        }
        
        internal static string ReportIntervalExplanation {
            get {
                return ResourceManager.GetString("ReportIntervalExplanation", resourceCulture);
            }
        }
        
        internal static string ReportUriAggregateExplanation {
            get {
                return ResourceManager.GetString("ReportUriAggregateExplanation", resourceCulture);
            }
        }
        
        internal static string ReportUriForensicExplanation {
            get {
                return ResourceManager.GetString("ReportUriForensicExplanation", resourceCulture);
            }
        }
        
        internal static string SubDomainPolicyNoneExplanation {
            get {
                return ResourceManager.GetString("SubDomainPolicyNoneExplanation", resourceCulture);
            }
        }
        
        internal static string SubDomainPolicyQuarantineExplanation {
            get {
                return ResourceManager.GetString("SubDomainPolicyQuarantineExplanation", resourceCulture);
            }
        }
        
        internal static string SubDomainPolicyRejectExplanation {
            get {
                return ResourceManager.GetString("SubDomainPolicyRejectExplanation", resourceCulture);
            }
        }
        
        internal static string VersionDmarc1Explanation {
            get {
                return ResourceManager.GetString("VersionDmarc1Explanation", resourceCulture);
            }
        }
    }
}
