//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailCheck.Dmarc.Poller.Rules {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DmarcRulesMarkdownResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DmarcRulesMarkdownResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MailCheck.Dmarc.Poller.Rules.DmarcRulesMarkdownResource", typeof(DmarcRulesMarkdownResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### Publish a DMARC record to enable DMARC reporting
        ///
        ///_This won&apos;t affect your email deliverability and will enable reporting to Mail Check_
        ///
        ///This tells anyone receiving email from you that:
        ///
        ///- you have a DMARC policy (v=DMARC1)
        ///- any messages that fail DMARC checks should still be delivered (p=none)
        ///- any messages that fail DMARC checks should still be delivered for any subdomains (sp=none)
        ///- they should send reports of email received to the NCSC Mail Check service (rua=mailto:dmarc-rua@mailcheck.s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NoDmarcErrorMessage {
            get {
                return ResourceManager.GetString("NoDmarcErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like there are multiple DMARC records for this domain, this isn&apos;t valid as there can only be one.
        ///This is often because a new record has been created to progress policy to quarantine or reject
        ///but the old record has been left in place. Please delete the extra record to clear this message.
        /// </summary>
        public static string OnlyOneDmarcRecordErrorMessage {
            get {
                return ResourceManager.GetString("OnlyOneDmarcRecordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DMARC exists to publish a policy, you need to add one of the following to your DMARC record:
        ///
        ///- `p=none` Report only, don&apos;t drop any emails.
        ///- `p=quarantine` Request that email providers move this email to the spam folder, and report back.
        ///- `p=reject` Request that email providers silently drop this email and report back..
        /// </summary>
        public static string PolicyTagMustExistErrorMessage {
            get {
                return ResourceManager.GetString("PolicyTagMustExistErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This DMARC record includes the same aggregate reporting destination twice in the rua tag, the duplicate entry should be removed.
        ///
        ///`dmarc record with duplicate removed`.
        /// </summary>
        public static string RuaTagShouldNotContainDuplicateUrisErrorMessage {
            get {
                return ResourceManager.GetString("RuaTagShouldNotContainDuplicateUrisErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your DMARC record contains the wrong email address for Mail Check aggregate report processing.
        ///
        ///Please change your DMARC record to be:
        ///
        ///{0}.
        /// </summary>
        public static string RuaTagShouldNotHaveMisconfiguredMailCheckMailboxErrorMessage {
            get {
                return ResourceManager.GetString("RuaTagShouldNotHaveMisconfiguredMailCheckMailboxErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This DMARC record has requested mail servers to send aggregate reports to {0} destinations.
        ///
        ///Please be aware that email servers are only obliged to deliver to the first two.
        ///Any extra destinations may get a random selection of reports giving misleading statistics.
        ///
        ///[From the DMARC RFC:](https://tools.ietf.org/html/rfc7489#section-6.2)
        ///
        ///`A report is normally sent to each listed URI in the order provided by the Domain Owner. Receivers MAY impose a limit on the number of URIs to which they will send rep [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RuaTagShouldNotHaveMoreThanTwoUrisErrorMessage {
            get {
                return ResourceManager.GetString("RuaTagShouldNotHaveMoreThanTwoUrisErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This DMARC record is using an unsupported method of delivering aggregate reports than mailto.
        ///
        ///It&apos;s most likely that mailto has a spelling mistake, please investigate..
        /// </summary>
        public static string RuaTagsShouldBeMailToErrorMessage {
            get {
                return ResourceManager.GetString("RuaTagsShouldBeMailToErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DMARC record does not contain the NCSC Mail Check email address, it&apos;s fine to use other tools but be aware that we won&apos;t be able to help you investigate email abuse, and you won&apos;t see any reporting in Mail Check.
        ///
        ///If you would like Mail Check to receive a copy of your reports, then please change your record to:
        ///
        ///{0}.
        /// </summary>
        public static string RuaTagsShouldContainDmarcServiceMailBoxErrorMessage {
            get {
                return ResourceManager.GetString("RuaTagsShouldContainDmarcServiceMailBoxErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This DMARC record is using a different method of delivering forensic reports than email (mailto:)
        ///The email method is the only one that is well supported so we don&apos;t recommend using others.
        ///
        ///It&apos;s most likely that this DMARC record has a spelling mistake mailto or is otherwise misconfigured, please investigate..
        /// </summary>
        public static string RufTagShouldBeMailToErrorMessage {
            get {
                return ResourceManager.GetString("RufTagShouldBeMailToErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This DMARC record has requested mail servers to send forensic reports to {0} destinations.
        ///
        ///Please be aware that email servers are only obliged to deliver to the first two.
        ///Any extra destinations may get a random selection of reports or none at all.
        ///
        ///[From the DMARC RFC:](https://tools.ietf.org/html/rfc7489#section-6.2)
        ///
        ///`A report is normally sent to each listed URI in the order provided by the Domain Owner. Receivers MAY impose a limit on the number of URIs to which they will send reports but MUST s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RufTagShouldNotHaveMoreThanTwoUrisErrorMessage {
            get {
                return ResourceManager.GetString("RufTagShouldNotHaveMoreThanTwoUrisErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A DMARC policy will only cascade down to subdomains if the record is on an organisation domain.
        ///
        ///An organisation domain is one level below a suffix that is listed on the [public suffix list](https://publicsuffix.org/)
        ///
        ///If a subdomain policy is defined on any domain below an organisational domain then it will have no effect.
        ///
        ///You may wish to create a DMARC record on any subdomains to override the organisational domain&apos;s subdomain policy
        ///
        ///[Read more about organizational domains in the DMARC RFC](https [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SubDomainIneffectualErrorMessage {
            get {
                return ResourceManager.GetString("SubDomainIneffectualErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DMARC policies aren&apos;t aren&apos;t intended to be published for top level domains that appear on the [public suffix list](https://publicsuffix.org/)
        ///
        ///The standard does not define the behaviour, so you are likely to see mixed results..
        /// </summary>
        public static string TldDmarcWeaklyDefinedMessage {
            get {
                return ResourceManager.GetString("TldDmarcWeaklyDefinedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A DMARC record must always start with v=DMARC1 to be valid.
        ///This record starts with {0} which is a misconfiguration..
        /// </summary>
        public static string VersionMustBeFirstTagErrorMessage {
            get {
                return ResourceManager.GetString("VersionMustBeFirstTagErrorMessage", resourceCulture);
            }
        }
    }
}
