//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailCheck.Dmarc.Poller.Rules {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DmarcRulesMarkdownResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DmarcRulesMarkdownResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MailCheck.Dmarc.Poller.Rules.DmarcRulesMarkdownResource", typeof(DmarcRulesMarkdownResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string NoDmarcErrorMessage {
            get {
                return ResourceManager.GetString("NoDmarcErrorMessage", resourceCulture);
            }
        }
        
        public static string MigrationNoDmarcErrorMessage {
            get {
                return ResourceManager.GetString("MigrationNoDmarcErrorMessage", resourceCulture);
            }
        }
        
        public static string OnlyOneDmarcRecordErrorMessage {
            get {
                return ResourceManager.GetString("OnlyOneDmarcRecordErrorMessage", resourceCulture);
            }
        }
        
        public static string PolicyTagMustExistErrorMessage {
            get {
                return ResourceManager.GetString("PolicyTagMustExistErrorMessage", resourceCulture);
            }
        }
        
        public static string RuaTagShouldNotHaveMoreThanTwoUrisErrorMessage {
            get {
                return ResourceManager.GetString("RuaTagShouldNotHaveMoreThanTwoUrisErrorMessage", resourceCulture);
            }
        }
        
        public static string RuaTagsShouldBeMailToErrorMessage {
            get {
                return ResourceManager.GetString("RuaTagsShouldBeMailToErrorMessage", resourceCulture);
            }
        }
        
        public static string RufTagShouldBeMailToErrorMessage {
            get {
                return ResourceManager.GetString("RufTagShouldBeMailToErrorMessage", resourceCulture);
            }
        }
        
        public static string RufTagShouldNotHaveMoreThanTwoUrisErrorMessage {
            get {
                return ResourceManager.GetString("RufTagShouldNotHaveMoreThanTwoUrisErrorMessage", resourceCulture);
            }
        }
        
        public static string SubDomainIneffectualErrorMessage {
            get {
                return ResourceManager.GetString("SubDomainIneffectualErrorMessage", resourceCulture);
            }
        }
        
        public static string TldDmarcWeaklyDefinedMessage {
            get {
                return ResourceManager.GetString("TldDmarcWeaklyDefinedMessage", resourceCulture);
            }
        }
        
        public static string VersionMustBeFirstTagErrorMessage {
            get {
                return ResourceManager.GetString("VersionMustBeFirstTagErrorMessage", resourceCulture);
            }
        }
    }
}
